services:
  - type: web
    name: web
    buildCommand: python3 -m pip install -r requirements.txt
    startCommand: gunicorn -b :$PORT src.app:app
    env:
      - key: PYTHON_VERSION
        value: "3.11"
